CREATE TYPE "tenant_status" AS ENUM (
  'active',
  'suspended',
  'inactive'
);

CREATE TYPE "order_status" AS ENUM (
  'pending',
  'processing',
  'shipped',
  'completed',
  'cancelled'
);

CREATE TYPE "payment_status" AS ENUM (
  'pending',
  'successful',
  'failed'
);

CREATE TYPE "payment_method" AS ENUM (
  'mastercard',
  'visa',
  'american_express',
  'paypal',
  'cash'
);

CREATE TYPE "shipment_status" AS ENUM (
  'pending',
  'packed',
  'shipped',
  'delivered',
  'returned',
  'cancelled'
);

CREATE TABLE "tenants" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "domain" varchar UNIQUE NOT NULL,
  "status" tenant_status DEFAULT 'active',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tenant_id" integer NOT NULL,
  "role_id" integer NOT NULL,
  "name" varchar,
  "email" varchar NOT NULL,
  "password_hash" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tenant_id" integer NOT NULL,
  "name" varchar NOT NULL
);

CREATE TABLE "permissions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tenant_id" integer NOT NULL,
  "name" varchar NOT NULL
);

CREATE TABLE "role_permissions" (
  "role_id" integer NOT NULL,
  "permission_id" integer NOT NULL,
  "tenant_id" integer NOT NULL,
  PRIMARY KEY ("tenant_id", "role_id", "permission_id")
);

CREATE TABLE "pages" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tenant_id" integer NOT NULL,
  "slug" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "page_sections" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "page_id" integer NOT NULL,
  "tenant_id" integer NOT NULL,
  "content" text,
  "metadata" jsonb,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "page_files" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tenant_id" integer NOT NULL,
  "page_id" integer NOT NULL,
  "path" varchar,
  "metadata" jsonb,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "forms" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tenant_id" integer NOT NULL,
  "page_id" integer,
  "title" varchar,
  "slug" varchar NOT NULL,
  "metadata" jsonb,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "questions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tenant_id" integer NOT NULL,
  "form_id" integer NOT NULL,
  "is_required" bool,
  "value" text,
  "position" integer,
  "metadata" jsonb,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "form_submissions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tenant_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "form_id" integer NOT NULL,
  "metadata" jsonb,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "answers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tenant_id" integer NOT NULL,
  "question_id" integer NOT NULL,
  "submission_id" integer NOT NULL,
  "value" text,
  "metadata" jsonb,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "patients" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "tenant_id" integer NOT NULL,
  "birthdate" date NOT NULL,
  "gender" varchar,
  "phone_number" varchar,
  "clinical_history" jsonb
);

CREATE TABLE "consultations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tenant_id" integer NOT NULL,
  "patient_id" integer NOT NULL,
  "doctor_id" integer NOT NULL,
  "form_id" integer,
  "symptoms" varchar,
  "current_medications" varchar,
  "diagnosis" varchar,
  "tests" varchar,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tenant_id" integer NOT NULL,
  "slug" varchar NOT NULL,
  "title" varchar,
  "description" text,
  "price" decimal CHECK (price >= 0),
  "prescription_required" bool,
  "image" varchar,
  "stock_quantity" integer CHECK (stock_quantity >= 0),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "prescriptions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tenant_id" integer NOT NULL,
  "consultation_id" integer NOT NULL,
  "usage_instructions" varchar,
  "other_medications" varchar,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tenant_id" integer NOT NULL,
  "parent_id" integer,
  "name" varchar,
  "slug" varchar NOT NULL,
  "description" text
);

CREATE TABLE "prescription_products" (
  "prescription_id" integer NOT NULL,
  "product_id" integer NOT NULL,
  "tenant_id" integer NOT NULL,
  PRIMARY KEY ("tenant_id", "prescription_id", "product_id")
);

CREATE TABLE "product_categories" (
  "product_id" integer NOT NULL,
  "category_id" integer NOT NULL,
  "tenant_id" integer NOT NULL,
  PRIMARY KEY ("tenant_id", "product_id", "category_id")
);

CREATE TABLE "orders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "tenant_id" integer NOT NULL,
  "status" order_status NOT NULL DEFAULT 'pending',
  "total_amount" decimal NOT NULL,
  "shipping_address" varchar NOT NULL,
  "billing_address" varchar,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "shipments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tenant_id" integer NOT NULL,
  "order_id" integer NOT NULL,
  "status" shipment_status NOT NULL DEFAULT 'pending',
  "carrier" varchar,
  "tracking_number" varchar,
  "recipient_name" varchar NOT NULL,
  "address_line1" varchar NOT NULL,
  "address_line2" varchar,
  "city" varchar NOT NULL,
  "state" varchar,
  "postal_code" varchar NOT NULL,
  "country_code" varchar NOT NULL,
  "shipped_at" timestamp,
  "delivered_at" timestamp,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "order_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tenant_id" integer NOT NULL,
  "order_id" int NOT NULL,
  "product_id" int NOT NULL,
  "quantity" int NOT NULL CHECK (quantity > 0)
);

CREATE TABLE "payments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer NOT NULL,
  "tenant_id" integer NOT NULL,
  "payment_method" payment_method NOT NULL,
  "status" payment_status DEFAULT 'pending',
  "amount" decimal NOT NULL,
  "transaction_id" varchar,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE UNIQUE INDEX ON "users" ("tenant_id", "id");

CREATE UNIQUE INDEX ON "users" ("tenant_id", "email");

CREATE UNIQUE INDEX ON "roles" ("tenant_id", "id");

CREATE UNIQUE INDEX ON "roles" ("tenant_id", "name");

CREATE UNIQUE INDEX ON "permissions" ("tenant_id", "id");

CREATE UNIQUE INDEX ON "permissions" ("tenant_id", "name");

CREATE UNIQUE INDEX ON "pages" ("tenant_id", "id");

CREATE UNIQUE INDEX ON "pages" ("tenant_id", "slug");

CREATE UNIQUE INDEX ON "page_sections" ("tenant_id", "id");

CREATE UNIQUE INDEX ON "forms" ("tenant_id", "id");

CREATE UNIQUE INDEX ON "forms" ("tenant_id", "slug");

CREATE UNIQUE INDEX ON "questions" ("tenant_id", "id");

CREATE UNIQUE INDEX ON "form_submissions" ("tenant_id", "id");

CREATE UNIQUE INDEX ON "answers" ("tenant_id", "id");

CREATE UNIQUE INDEX ON "answers" ("submission_id", "question_id");

CREATE UNIQUE INDEX ON "patients" ("tenant_id", "id");

CREATE UNIQUE INDEX ON "patients" ("tenant_id", "user_id");

CREATE UNIQUE INDEX ON "consultations" ("tenant_id", "id");

CREATE UNIQUE INDEX ON "products" ("tenant_id", "id");

CREATE UNIQUE INDEX ON "products" ("tenant_id", "slug");

CREATE UNIQUE INDEX ON "prescriptions" ("tenant_id", "id");

CREATE UNIQUE INDEX ON "categories" ("tenant_id", "id");

CREATE UNIQUE INDEX ON "categories" ("tenant_id", "slug");

CREATE UNIQUE INDEX ON "orders" ("tenant_id", "id");

CREATE UNIQUE INDEX ON "shipments" ("tenant_id", "id");

CREATE INDEX ON "shipments" ("tenant_id", "order_id");

CREATE INDEX ON "shipments" ("tenant_id", "tracking_number");

CREATE UNIQUE INDEX ON "order_items" ("tenant_id", "id");

COMMENT ON COLUMN "forms"."slug" IS 'Enables embedding a form in multiple pages';

COMMENT ON COLUMN "questions"."value" IS 'The actual question';

COMMENT ON COLUMN "answers"."value" IS 'The actual answer';

COMMENT ON COLUMN "patients"."clinical_history" IS 'Optional patient history such as previous illnesses, allergies, smoking, alcohol or other patient info';

COMMENT ON COLUMN "consultations"."tests" IS 'Medical examinations necessary to diagnose a patient';

COMMENT ON COLUMN "shipments"."country_code" IS 'ISO-3166 alpha-2 recommended';

COMMENT ON COLUMN "payments"."transaction_id" IS 'Foreign transaction ID from a third party service';

ALTER TABLE "users" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id");

ALTER TABLE "roles" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("tenant_id", "role_id") REFERENCES "roles" ("tenant_id", "id");

ALTER TABLE "permissions" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id");

ALTER TABLE "role_permissions" ADD FOREIGN KEY ("tenant_id", "role_id") REFERENCES "roles" ("tenant_id", "id");

ALTER TABLE "role_permissions" ADD FOREIGN KEY ("tenant_id", "permission_id") REFERENCES "permissions" ("tenant_id", "id");

ALTER TABLE "role_permissions" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id");

ALTER TABLE "pages" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id");

ALTER TABLE "page_sections" ADD FOREIGN KEY ("tenant_id", "page_id") REFERENCES "pages" ("tenant_id", "id");

ALTER TABLE "page_sections" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id");

ALTER TABLE "page_files" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id");

ALTER TABLE "page_files" ADD FOREIGN KEY ("tenant_id", "page_id") REFERENCES "pages" ("tenant_id", "id");

ALTER TABLE "forms" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id");

ALTER TABLE "forms" ADD FOREIGN KEY ("tenant_id", "page_id") REFERENCES "pages" ("tenant_id", "id");

ALTER TABLE "questions" ADD FOREIGN KEY ("tenant_id", "form_id") REFERENCES "forms" ("tenant_id", "id");

ALTER TABLE "questions" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id");

ALTER TABLE "form_submissions" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id");

ALTER TABLE "form_submissions" ADD FOREIGN KEY ("tenant_id", "user_id") REFERENCES "users" ("tenant_id", "id");

ALTER TABLE "form_submissions" ADD FOREIGN KEY ("tenant_id", "form_id") REFERENCES "forms" ("tenant_id", "id");

ALTER TABLE "answers" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id");

ALTER TABLE "answers" ADD FOREIGN KEY ("tenant_id", "question_id") REFERENCES "questions" ("tenant_id", "id");

ALTER TABLE "answers" ADD FOREIGN KEY ("tenant_id", "submission_id") REFERENCES "form_submissions" ("tenant_id", "id");

ALTER TABLE "patients" ADD FOREIGN KEY ("tenant_id", "user_id") REFERENCES "users" ("tenant_id", "id");

ALTER TABLE "patients" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id");

ALTER TABLE "consultations" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id");

ALTER TABLE "consultations" ADD FOREIGN KEY ("tenant_id", "patient_id") REFERENCES "patients" ("tenant_id", "id");

ALTER TABLE "consultations" ADD FOREIGN KEY ("tenant_id", "doctor_id") REFERENCES "users" ("tenant_id", "id");

ALTER TABLE "consultations" ADD FOREIGN KEY ("tenant_id", "form_id") REFERENCES "forms" ("tenant_id", "id");

ALTER TABLE "prescriptions" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id");

ALTER TABLE "consultations" ADD FOREIGN KEY ("tenant_id", "id") REFERENCES "prescriptions" ("tenant_id", "consultation_id");

ALTER TABLE "products" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id");

ALTER TABLE "prescription_products" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id");

ALTER TABLE "prescription_products" ADD FOREIGN KEY ("tenant_id", "prescription_id") REFERENCES "prescriptions" ("tenant_id", "id");

ALTER TABLE "prescription_products" ADD FOREIGN KEY ("tenant_id", "product_id") REFERENCES "products" ("tenant_id", "id");

ALTER TABLE "categories" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id");

ALTER TABLE "categories" ADD FOREIGN KEY ("tenant_id", "parent_id") REFERENCES "categories" ("tenant_id", "id");

ALTER TABLE "product_categories" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id");

ALTER TABLE "product_categories" ADD FOREIGN KEY ("tenant_id", "product_id") REFERENCES "products" ("tenant_id", "id");

ALTER TABLE "product_categories" ADD FOREIGN KEY ("tenant_id", "category_id") REFERENCES "categories" ("tenant_id", "id");

ALTER TABLE "orders" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("tenant_id", "user_id") REFERENCES "users" ("tenant_id", "id");

ALTER TABLE "shipments" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id");

ALTER TABLE "shipments" ADD FOREIGN KEY ("tenant_id", "order_id") REFERENCES "orders" ("tenant_id", "id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("tenant_id", "order_id") REFERENCES "orders" ("tenant_id", "id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("tenant_id", "product_id") REFERENCES "products" ("tenant_id", "id");

ALTER TABLE "payments" ADD FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("tenant_id", "id") REFERENCES "payments" ("tenant_id", "order_id");
